import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shares/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hongducdev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1240px] w-full mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
