import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="bg-zinc-50 antialiased bg-dot-zinc-400/[0.2] w-full min-h-screen">
          <Navbar />
          <div className="p-4 lg:p-8">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
